[versions]
datastoreCore = "1.0.0"
kotlinSerialization = "1.9.21"
kotlinxSerializationJson = "1.6.0"
ktx = "1.9.0"
lifecycle = "2.6.2"
androidGradlePlugin = "8.1.1"
kotlin = "1.9.20"
activity-compose = "1.8.0"
google-services = "4.4.0"
compose-bom = "2023.10.01"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso = "3.5.1"
firebase-bom = "32.5.0"
material-icons-extended = "1.5.3"
appcompat = "1.6.1"
material = "1.10.0"
navigation-version = "2.7.5"
core-splashscreen = "1.0.0"
camerax-version = "1.3.0"
tensorflow = "0.4.0"
tensorflow-gpu = "2.9.0"
constraintlayout = "2.1.4"

[libraries]
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastoreCore" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastoreCore" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class", version="1.1.2" }
material-compose = { group = "androidx.compose.material", name = "material", version = "1.5.4" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons-extended"  }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version = "1.0.1" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation-version" }

#Splash Screen
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }

androidx-monitor = { group = "androidx.test", name = "monitor", version = "1.6.1" }

#CameraX libraries
camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax-version" }
camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "camerax-version" }
camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "camerax-version" }
camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "camerax-version" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camerax-version" }
camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "camerax-version" }

#tensorflow libraries
tensorflow-lite-task = { group = "org.tensorflow", name = "tensorflow-lite-task-vision", version.ref = "tensorflow" }
tensorflow-lite-gpuDelegatePlugin = { group = "org.tensorflow", name = "tensorflow-lite-gpu-delegate-plugin", version.ref = "tensorflow" }
tensorflow-lite-gpu = { group = "org.tensorflow", name = "tensorflow-lite-gpu", version.ref = "tensorflow-gpu" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }